idk dude
urfu-2018/typescript-task-1 pull request #1
Opened 2018-12-15 07:53 UTC by Yewert

2018-12-15 07:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 5 из 5

2018-12-18 19:21 UTC, evgenymarkov requested changes
🍅

2018-12-18 19:21 UTC, evgenymarkov commented on src/state/news/types.ts
> +export function articleToString(article: IArticle): string {
Эта функция здесь не к месту. В файле хранятся описания используемых типов.

2018-12-18 19:21 UTC, evgenymarkov commented on src/state/weather/types.ts
> +export function measurementToString(measurement: IMeasurement) {
И эта тоже. Функции правильные, они формируют некоторое "отображение" тех данных, которые ты передаёшь. Ну а всё что связано с отображением лежит в директории `views`.

2018-12-18 19:21 UTC, evgenymarkov commented on src/utils/observable/index.ts
> +    constructor() {
Лучше визуально отделять поля класса и конструктор.

2018-12-18 19:21 UTC, evgenymarkov commented on src/utils/observable/index.ts
> +        this.observers = new Set<IObserver>();
Конструктор можно не использовать в данном случае. Инициализацию полей можно провести прямо при их объявлении: 

```typescript
private readonly observers = new Set<IObserver>();
```

TypeScript выведет сам правильный тип данных для `observers`.

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/desktop.ts
> +        if (DesktopView.isInstanceOfINewsState(observable)) {
Хороший эксперимент с кастомными Type Guards, но в данном случае достаточно базового `instanceof` и проверить им, что observable это NewsState или WeatherState.

https://basarat.gitbooks.io/typescript/docs/types/typeGuard.html

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/desktop.ts
> +        this.render();
Вкусовщина, но управляющие конструкции вроде `while`/`for`/`if`/`switch`/`return` лучше отделять пустыми строками

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/desktop.ts
> +            '<div class="desktop">\n' + articles.concat(reports).join('\n') + '\n</div>';
Лучше переписать эту конструкцию используя интерполяцию строк:

```typescript
`<div class="desktop">\n${articles.concat(reports).join('\n')}\n</div>`
```

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/desktop.ts
> +        console.log(rendered);
Переменная `rendered` кажется лишней. Она не несёт дополнительного профита по скорости или читаемости кода.

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/desktop.ts
> +            .slice(this.news.length - 3)
"Магические числа" в коде лучше заменять именованными константами. В данном случае подойдут статические поля класса, в которые надо записать количество выводимых новостей и измерений погоды.

2018-12-18 19:21 UTC, evgenymarkov commented on src/views/mobile.ts
> +        console.log(rendered);
Все замечания по этому файлу аналогичны тем что оставил в `desktop.tsx`

2018-12-18 19:42 UTC, evgenymarkov commented on src/views/desktop.ts
> +            .slice(this.news.length - 3)
Здесь есть баг, который не вскрывают тесты. В slice при некоторых обстоятельствах может быть передано отрицательное значение.

2018-12-18 20:31 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-18 20:31 UTC, honest-hrundel commented
@evgenymarkov обрати внимание: решено доп. задание

2018-12-19 13:01 UTC, evgenymarkov requested changes
🍅

Сделал лишнюю работу реализовав глубокое и не универсальное сравнение.

В условии задачи сказано "Избавьтесь от лишних вызовов метода render(), реализовав в экранах **поверхностное** сравнение новых данных с теми, которые были показаны во время прошлого вызова"

Погугли shallow compare или shallow diff. Часто такое употребляют в контексте разработки с использованием React.

2018-12-21 13:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-21 13:15 UTC, honest-hrundel commented
@evgenymarkov обрати внимание: решено доп. задание

2018-12-21 21:34 UTC, evgenymarkov approved these changes
🍏

2018-12-21 21:34 UTC, evgenymarkov commented on src/views/comparer.ts
> +export function changed(a: any[], b: any[]): boolean {
Крайне желательно чтобы в названиях функций был глагол. `changed` больше напоминает переменную в которую сохранили какой-то флаг.

2018-12-21 21:35 UTC, closed without merging