Петряшов Андрей
urfu-2018/typescript-task-1 pull request #23
Opened 2018-12-19 19:07 UTC by mopozko

2018-12-19 19:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 7

2018-12-19 19:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-19 19:38 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-23 15:31 UTC, nikshel requested changes
Прикольная задумка с базовым классом 👍 
Осталось пару вещей поправить

2018-12-23 15:31 UTC, nikshel commented on src/utils/observable/index.ts
> +    private observers: Set<IObserver> = new Set<IObserver>();
Тип поля в такой ситуации можно не писать, потому что из-за присваивания с `new` он и так понятен

2018-12-23 15:31 UTC, nikshel commented on src/views/desktop.ts
> +    protected deviceType: string = 'desktop';
Тут тоже тип можно не писать, и так понятно

2018-12-23 15:31 UTC, nikshel commented on src/views/index.ts
> +        }
В задании сказано, что нужно сделать "поверхностное сравнение данных".
Представь, что `getContent` это дорогая операция, и мы не хотим ее вызывать, если данные не изменились

2018-12-23 15:31 UTC, nikshel commented on src/views/index.ts
> +export abstract class View implements IObserver, IView {
Класс лучше назвать `BaseView` или `AbstractView`

2018-12-27 11:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-27 11:43 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-28 09:10 UTC, nikshel approved these changes

2018-12-28 09:11 UTC, closed without merging