Ермаков Степан
urfu-2018/typescript-task-1 pull request #32
Opened 2018-12-20 18:23 UTC by predatorfromekb

first

2018-12-20 18:23 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 5 из 5

2018-12-22 08:13 UTC, evgenymarkov requested changes
🍅

2018-12-22 08:13 UTC, evgenymarkov commented on src/utils/observable/index.ts
> +    private readonly observers: IObserver[] = [];
В данном случае можно было воспользоваться структурой данных Set. Код удаления станет чуть проще

2018-12-22 08:13 UTC, evgenymarkov commented on src/utils/observable/index.ts
> +            observer.update(this);
Блок можно опустить и уложить всё в одну строку:

```typescript
this.observers.forEach(observer => observer.update(this));
```

2018-12-22 08:13 UTC, evgenymarkov commented on src/views/renderData.ts
> +export abstract class RenderDataContainer {
Класс не представляет какой-то большой ценности в коде, но ограничивает тебя в возможности унаследоваться от чего-либо ещё кроме RenderDataContainer. Не страшно такое небольшое количество логики продублировать в нескольких View.

2018-12-22 08:13 UTC, evgenymarkov commented on src/views/renderData.ts
> +import { IObservable } from '../utils/observable/types';
Лучше называть файлы с исходным кодом в [kebab-case](http://wiki.c2.com/?KebabCase)

2018-12-22 08:13 UTC, evgenymarkov commented on src/views/mobile.ts
> +        this.renderData += RenderDataProvider.provide(observable, 1, 1);
Попробуй в `index.ts` добавить ещё пару вызовов `setArticles` или `setMeasurements`. Увидишь, что показываются ещё и старые данные, этого быть не должно.

2018-12-22 08:13 UTC, evgenymarkov commented on src/views/mobile.ts
> +        this.renderData += RenderDataProvider.provide(observable, 1, 1);
![image](https://user-images.githubusercontent.com/16443248/50372179-39ff5900-05eb-11e9-8c04-0b0639ed8716.png)
Так это выглядело бы в интерфейсе

2018-12-27 17:35 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 5 из 5

2018-12-27 17:37 UTC, predatorfromekb commented on src/views/mobile.ts
> +        this.renderData += RenderDataProvider.provide(observable, 1, 1);
ой, косякнул

2018-12-27 17:37 UTC, predatorfromekb commented on src/views/mobile.ts
> +        this.renderData += RenderDataProvider.provide(observable, 1, 1);
странно, что тестов нету на этот кейс

2018-12-27 17:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 5

2018-12-27 18:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 5 из 5

2018-12-27 18:30 UTC, predatorfromekb commented
🍏

2018-12-28 19:26 UTC, evgenymarkov requested changes
🍅

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/desktop.ts
> +    get newsData(): string {
Геттеры и сеттеры в твоём случае просто складывают и отдают данные хранящиеся в приватных полях, а снаружи newsData и weatherData никем не используются поэтому и необходимости в них нет, они только усложняют код.

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/desktop.ts
> +            this.weatherData = RenderDataProvider.provideMeasurements(observable, 2);
Магические числа в коде остались, сделай их именованными константами

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/desktop.ts
> +    private _newsData: string = '';
Тип данных выведется автоматически при присваивании значения

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/mobile.ts
> +    private _newsData: string = '';
Все замечания аналогичны файлу с десктопной вьюшкой

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/render-data.ts
> +    public static provideArticles(observable: INewsState, articlesCount: number): string {
Всё это можно уложить в одну цепочку: getArticles, затем slice, потом map.

2018-12-28 19:26 UTC, evgenymarkov commented on src/views/render-data.ts
> +        let result: string = '';
Замечания аналогичные как и для метода provideArticles

2018-12-29 17:08 UTC, predatorfromekb commented on src/views/desktop.ts
> +    private _newsData: string = '';
а можно как то настроить интелисенс вебшторма, чтобы он выбрасывал подсказки, например что можно опустить явное указывание типа?

2018-12-29 17:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 5

2018-12-29 17:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 5

2018-12-29 17:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 5 из 5

2018-12-29 17:30 UTC, predatorfromekb commented on src/views/render-data.ts
> +    public static provideArticles(observable: INewsState, articlesCount: number): string {
getArticles, slice, map и reduce, для получения строки

2018-12-29 17:30 UTC, predatorfromekb commented
🍏

2018-12-30 10:02 UTC, evgenymarkov approved these changes

2018-12-30 10:02 UTC, evgenymarkov commented on src/views/render-data.ts
> +            .reduce((result, value) => result + value, '');
Можно заменить на `join('')` и убрать возвращаемое значение функции.
А для reduce можно указать возвращаемое значение с помощью дженерика: `reduce<string>(...)`

2018-12-30 10:02 UTC, evgenymarkov commented on src/views/mobile.ts
> +        const ARTICLES_COUNT = 1;
Можно не инициализировать эти переменные каждый раз, а сложить в статическое поле класса:

```typescript
private static readonly ARTICLES_COUNT = 1;
```

2018-12-30 10:02 UTC, closed without merging