Летуновский Максим
urfu-2018/typescript-task-1 pull request #36
Opened 2018-12-21 06:27 UTC by MaxtiCorn

2018-12-21 06:28 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-21 06:28 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-12-21 06:54 UTC, SemyonMakhaev requested changes
🍅

2018-12-21 06:54 UTC, SemyonMakhaev commented on src/state/news/index.ts
> +        super();
Можно этот метод убрать, наследование полей и методов произойдёт по умолчанию

2018-12-21 06:54 UTC, SemyonMakhaev commented on src/state/weather/index.ts
> +        super();
>Можно этот метод убрать, наследование полей и методов произойдёт по умолчанию

Аналогично

2018-12-21 06:54 UTC, SemyonMakhaev commented on src/utils/observable/index.ts
> +    constructor(private observers: Set<IObserver> = new Set<IObserver>()) {}
Это поле можно инициализировать не в конструкторе, а непосредственно внутри тела класса. Можно добавить модификатор доступа `readonly`

2018-12-21 06:54 UTC, SemyonMakhaev commented on src/views/abstractView.ts
> +        private oldMessage?: string
Конструктор принимает очень много параметров. В таких случаях удачнее передавать их как именованные аргументы, то есть, в объекте.

Я думаю, что поля класса лучше записывать в теле этого класса, потому что тогда они более явно видны. Не нужно смотреть в объявление конструктора, чтобы понять, какие поля есть у класса. Но это обсуждаемо)

2018-12-21 07:06 UTC, MaxtiCorn commented on src/state/news/index.ts
> +        super();
Тут же идет наследование от Обсервабл и имплементация IСтейта, откуда взяться полю?

2018-12-21 07:06 UTC, MaxtiCorn commented on src/state/weather/index.ts
> +        super();
> Тут же идет наследование от Обсервабл и имплементация IСтейта, откуда взяться полю?

Аналогично

2018-12-21 07:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-21 07:16 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-12-21 08:21 UTC, SemyonMakhaev commented on src/state/news/index.ts
> +        super();
Понял тебя, да. Объявление поля в аргументах конструктора выглядит вообще неочевидно. Может быть, укажем явно? Перенесём декларацию в тело класса и будем присваивать ей значение в конструкторе?

2018-12-21 10:26 UTC, maksticorn commented on src/state/news/index.ts
> +        super();
Вроде как это фича тайпскрипта, благодаря которой можно значительно сократить код. Дело вкуса, но мне она нравится) Можно еще парочку аргументов против ее использования?

2018-12-21 12:48 UTC, SemyonMakhaev commented on src/state/news/index.ts
> +        super();
Ну если нравится, то ок. Согласен, вопрос достаточно субъективный. Давай оставим так

2018-12-21 12:54 UTC, SemyonMakhaev commented on src/views/abstractView.ts
> +        this.measurementsCount = measurementsCount;
Эти поля задаются сразу при передаче параметров. В теле конструктора ты их повторно перезаписываешь

2018-12-24 06:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-24 06:10 UTC, honest-hrundel commented
@SemyonMakhaev обрати внимание: решено доп. задание

2018-12-24 08:35 UTC, SemyonMakhaev approved these changes
🍏

2018-12-24 08:35 UTC, closed without merging