Утробин Тимофей
urfu-2018/typescript-task-1 pull request #50
Opened 2018-12-22 10:38 UTC by timofeyutrobin

2018-12-22 10:39 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 7

2018-12-22 10:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 5

2018-12-22 10:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-22 10:55 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2018-12-22 10:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-22 10:58 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2019-01-05 15:52 UTC, spt30 requested changes
🍅 Привет! Все классно, все круто, есть пара замечаний по кодстайлу, их поправишь и ок будет:

2019-01-05 15:52 UTC, spt30 commented on src/views/view.ts
> +    private articleToString(article: IArticle): string {
деструктор в аргументе функции и читать будет легче

нам тут совсем не обязательно знать, что ты назвал эту переменную `article`, тем более, что она нигде не используется

2019-01-05 15:52 UTC, spt30 commented on src/views/view.ts
> +        const formattedWeather = measurementsToShow.map(measurement =>
можно ведь просто `const formattedWeather = measurementsToShow.map(this.measurementToString)`
передаешь функцию, которая принимает один аргумент, то же самое будет

2019-01-05 15:52 UTC, spt30 commented on src/views/view.ts
> +        const formattedWeather = measurementsToShow.map(measurement =>
и выше тоже

2019-01-05 17:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2019-01-05 17:59 UTC, honest-hrundel commented
@spt30 обрати внимание: решено доп. задание

2019-01-05 18:05 UTC, spt30 commented
🍏K P A C U B O

2019-01-05 18:05 UTC, closed without merging