Волков Денис
urfu-2018/typescript-task-1 pull request #55
Opened 2019-01-03 06:25 UTC by Denchick

2019-01-03 06:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 5

2019-01-03 06:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 7

2019-01-03 06:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2019-01-03 06:45 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2019-01-03 06:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 7

2019-01-03 06:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 7

2019-01-03 07:17 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2019-01-03 07:17 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2019-01-03 07:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2019-01-03 07:44 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2019-01-04 05:26 UTC, nikshel requested changes

2019-01-04 05:26 UTC, nikshel commented on .gitignore
> +package-lock.json
А это откуда?

2019-01-04 05:26 UTC, nikshel commented on src/utils/observable/index.ts
> +        this.observers = this.observers.filter(o => o !== observer);
`o` - плохое имя для переменной

2019-01-04 05:26 UTC, nikshel commented on src/views/state.ts
> +            const newsState = observable as NewsState;
После проверки вида `X instanceof Y` и `typeof X === Y`  тайпскрипт сам уточняет тип переменной, так что тут можно обойтись без `as` и второй переменной

2019-01-04 05:26 UTC, nikshel commented on src/views/state.ts
> +            if (JSON.stringify(this.articles) === JSON.stringify(newArticles)) {
Во многих случаях эта проверка будет работать неправильно (например, если в двух статьях поля имеют равные значения, но идут в разном порядке)

Надо сделать поверхностное сравнение более надежным способом

2019-01-04 05:26 UTC, nikshel commented on src/views/types.ts
> +export enum ViewType {
👍

2019-01-04 05:26 UTC, nikshel commented on src/views/state.ts
> +    public viewType: ViewType;
Что-то я не вижу, чтобы значение этого поля где-то использовалось

2019-01-04 05:26 UTC, nikshel commented on src/views/helpers.ts
> +    public static getPrettyMeasurement(m: IMeasurement) {
`m` - плохое имя для переменной (даже если не получается влезть в ограничение по длине строки)

2019-01-04 05:26 UTC, nikshel commented on src/views/state.ts
> +export class ViewState {
👍

2019-01-04 05:26 UTC, nikshel commented on src/views/helpers.ts
> +        const prettyArticles = articles.map(a => Helpers.getPrettyArticle(a)).join('\n');
Вроде в `map` можно было бы написать ровно как в следующей строчке

2019-01-04 05:26 UTC, nikshel commented on src/views/helpers.ts
> +export abstract class Helpers {
Какой-то очень странный класс, честно говоря: абстрактный, с кучей статических методов, причем два из них могут быть приватными.

Кажется, из этого модуля можно экспортировать просто функцию. В TS, в отличие от C#, можно не писать класс на каждый чих

2019-01-04 05:26 UTC, nikshel commented on src/views/helpers.ts
> +        return result.join('\n');
👍

2019-01-04 05:39 UTC, Denchick commented on .gitignore
> +package-lock.json
Мне так другой  ментор [посоветовал](https://github.com/urfu-2018/javascript-task-2/pull/103#discussion_r244535738)

2019-01-04 05:43 UTC, Denchick commented on src/utils/observable/index.ts
> +        this.observers = this.observers.filter(o => o !== observer);
👍

2019-01-04 05:48 UTC, Denchick commented on src/views/state.ts
> +            const newsState = observable as NewsState;
👍

2019-01-04 05:50 UTC, Denchick commented on src/views/state.ts
> +    public viewType: ViewType;
Ну да, от него можно избавиться.

2019-01-04 05:55 UTC, Denchick commented on src/views/helpers.ts
> +    public static getPrettyMeasurement(m: IMeasurement) {
Хотел поспорить, но потом понял, как можно сделать лучше 👍

2019-01-04 05:55 UTC, Denchick commented on src/views/helpers.ts
> +        const prettyArticles = articles.map(a => Helpers.getPrettyArticle(a)).join('\n');
Я пытался, но линтер ругался

2019-01-04 06:00 UTC, Denchick commented on src/views/helpers.ts
> +export abstract class Helpers {
Сильно 👍

2019-01-04 06:24 UTC, nikshel commented on .gitignore
> +package-lock.json
А, у тебя другая версия ноды. Ну тогда ладно

2019-01-04 06:25 UTC, nikshel commented on src/views/helpers.ts
> +        const prettyArticles = articles.map(a => Helpers.getPrettyArticle(a)).join('\n');
А что говорит?

2019-01-04 06:35 UTC, Denchick commented on src/views/state.ts
> +            if (JSON.stringify(this.articles) === JSON.stringify(newArticles)) {
Кстати говоря, я же мог тут просто написать вот так: `if (this.articles === newArticles)`. 
А так, я что-то придумал, но выглядит это сомнительно.

2019-01-04 06:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2019-01-04 06:37 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2019-01-04 16:04 UTC, nikshel commented on src/views/state.ts
> +            if (JSON.stringify(this.articles) === JSON.stringify(newArticles)) {
> Кстати говоря, я же мог тут просто написать вот так

Это тоже неправильный способ, потому что так ты будешь сравнивать ссылки на массивы, не учитывая кейс, когда передали другой массив с теми же самыми объектами

2019-01-04 16:07 UTC, nikshel approved these changes

2019-01-04 16:07 UTC, nikshel commented on src/views/helpers.ts
> +    const prettyArticles = articles.map(a => getPrettyArticle(a)).join('\n');
Все-таки кажется, что `map(getPrettyArticle)` должен сработать

2019-01-04 16:07 UTC, nikshel commented on src/views/helpers.ts
> +    return first.every(element => second.includes(element));
Порядок бы тоже не помешало учесть

2019-01-04 16:07 UTC, closed without merging