Решение задачи Приключения Аркадия в Тайплэнде
urfu-2018/typescript-task-1 pull request #8
Opened 2018-12-16 09:18 UTC by AIBarabanshchikova

2018-12-16 09:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-16 09:19 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-23 15:07 UTC, nikshel requested changes

2018-12-23 15:07 UTC, nikshel commented on src/views/utils.ts
> +export function equal(old: any[], current: any[]) {
А давай максимально полно опишем тип массива так, чтобы:
1. `old` и `current` были либо `IArticle`, либо `IMeasurement`
2. сравнение точно было корректно

2018-12-24 18:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 7 из 7

2018-12-24 18:03 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-24 20:01 UTC, AIBarabanshchikova commented
🍏

2018-12-25 14:38 UTC, nikshel approved these changes

2018-12-25 14:38 UTC, nikshel commented on src/views/utils.ts
> +export function equal<T extends (IArticle) | (IMeasurement)>(old: T[], current: T[]) {
Можно было без круглых скобок

2018-12-25 14:38 UTC, closed without merging